- name: nginx installation
  hosts: web
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: installed
  - name: start the nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      

    
