- name: install nginx
  hosts: web1
  become: yes
  tasks:
  - name: install nginx if rhel
    ansible.builtin.dnf:
      name: nginx
      state: absent
    when: ansible_os_family == "REDHAT"

  - name: Install nginx if ubuntu
    ansible.builtin.apt:
      name: nginx
      state: absent
    when: ansible_os_family == "Debian"
  
